#############################################################################
# Makefile for building: nem-nem
# Generated by qmake (2.01a) (Qt 4.7.3) on: jeu. mai 26 00:49:20 2011
# Project:  nem-nem.pro
# Template: app
# Command: /data/bin/QtSDK/Desktop/Qt/473/gcc/bin/qmake -o Makefile nem-nem.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/default -I. -I../../bin/QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../bin/QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../bin/QtSDK/Desktop/Qt/473/gcc/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/data/bin/QtSDK/Desktop/Qt/473/gcc/lib
LIBS          = $(SUBLIBS)  -L/data/bin/QtSDK/Desktop/Qt/473/gcc/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /data/bin/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = automate.cpp \
		candidate.cpp \
		cellule.cpp \
		colorselectbutton.cpp \
		coord.cpp \
		default.cpp \
		die.cpp \
		dispenser.cpp \
		figure.cpp \
		gameboard.cpp \
		grid.cpp \
		gridmodel.cpp \
		historian.cpp \
		lancer.cpp \
		main.cpp \
		mat.cpp \
		nemnemevent.cpp \
		nemnemtools.cpp \
		nemnemwindow.cpp \
		player.cpp \
		score.cpp \
		sound.cpp \
		systemtools.cpp moc_automate.cpp \
		moc_colorselectbutton.cpp \
		moc_die.cpp \
		moc_gameboard.cpp \
		moc_grid.cpp \
		moc_gridmodel.cpp \
		moc_historian.cpp \
		moc_lancer.cpp \
		moc_nemnemtools.cpp \
		moc_nemnemwindow.cpp \
		moc_player.cpp \
		moc_score.cpp \
		qrc_nem-nem.cpp
OBJECTS       = automate.o \
		candidate.o \
		cellule.o \
		colorselectbutton.o \
		coord.o \
		default.o \
		die.o \
		dispenser.o \
		figure.o \
		gameboard.o \
		grid.o \
		gridmodel.o \
		historian.o \
		lancer.o \
		main.o \
		mat.o \
		nemnemevent.o \
		nemnemtools.o \
		nemnemwindow.o \
		player.o \
		score.o \
		sound.o \
		systemtools.o \
		moc_automate.o \
		moc_colorselectbutton.o \
		moc_die.o \
		moc_gameboard.o \
		moc_grid.o \
		moc_gridmodel.o \
		moc_historian.o \
		moc_lancer.o \
		moc_nemnemtools.o \
		moc_nemnemwindow.o \
		moc_player.o \
		moc_score.o \
		qrc_nem-nem.o
DIST          = ../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		nem-nem.pro
QMAKE_TARGET  = nem-nem
DESTDIR       = 
TARGET        = nem-nem

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_nemnemwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nem-nem.pro  ../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/default/qmake.conf ../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile nem-nem.pro
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../bin/QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile nem-nem.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/nem-nem1.0.0 || $(MKDIR) .tmp/nem-nem1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/nem-nem1.0.0/ && $(COPY_FILE) --parents automate.h candidate.h cellule.h colorselectbutton.h coord.h default.h defines.h die.h dispenser.h figure.h gameboard.h grid.h gridmodel.h historian.h lancer.h mat.h nemnemevent.h nemnemtools.h nemnemwindow.h player.h score.h sound.h systemtools.h .tmp/nem-nem1.0.0/ && $(COPY_FILE) --parents nem-nem.qrc .tmp/nem-nem1.0.0/ && $(COPY_FILE) --parents automate.cpp candidate.cpp cellule.cpp colorselectbutton.cpp coord.cpp default.cpp die.cpp dispenser.cpp figure.cpp gameboard.cpp grid.cpp gridmodel.cpp historian.cpp lancer.cpp main.cpp mat.cpp nemnemevent.cpp nemnemtools.cpp nemnemwindow.cpp player.cpp score.cpp sound.cpp systemtools.cpp .tmp/nem-nem1.0.0/ && $(COPY_FILE) --parents nemnemwindow.ui .tmp/nem-nem1.0.0/ && $(COPY_FILE) --parents nem-nem_en.ts .tmp/nem-nem1.0.0/ && (cd `dirname .tmp/nem-nem1.0.0` && $(TAR) nem-nem1.0.0.tar nem-nem1.0.0 && $(COMPRESS) nem-nem1.0.0.tar) && $(MOVE) `dirname .tmp/nem-nem1.0.0`/nem-nem1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/nem-nem1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_automate.cpp moc_colorselectbutton.cpp moc_die.cpp moc_gameboard.cpp moc_grid.cpp moc_gridmodel.cpp moc_historian.cpp moc_lancer.cpp moc_nemnemtools.cpp moc_nemnemwindow.cpp moc_player.cpp moc_score.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_automate.cpp moc_colorselectbutton.cpp moc_die.cpp moc_gameboard.cpp moc_grid.cpp moc_gridmodel.cpp moc_historian.cpp moc_lancer.cpp moc_nemnemtools.cpp moc_nemnemwindow.cpp moc_player.cpp moc_score.cpp
moc_automate.cpp: grid.h \
		defines.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		gameboard.h \
		systemtools.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		automate.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) automate.h -o moc_automate.cpp

moc_colorselectbutton.cpp: colorselectbutton.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) colorselectbutton.h -o moc_colorselectbutton.cpp

moc_die.cpp: defines.h \
		default.h \
		die.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) die.h -o moc_die.cpp

moc_gameboard.cpp: systemtools.h \
		default.h \
		defines.h \
		die.h \
		nemnemtools.h \
		mat.h \
		lancer.h \
		figure.h \
		sound.h \
		dispenser.h \
		gameboard.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) gameboard.h -o moc_gameboard.cpp

moc_grid.cpp: defines.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		grid.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) grid.h -o moc_grid.cpp

moc_gridmodel.cpp: defines.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		gridmodel.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) gridmodel.h -o moc_gridmodel.cpp

moc_historian.cpp: coord.h \
		defines.h \
		nemnemtools.h \
		nemnemevent.h \
		historian.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) historian.h -o moc_historian.cpp

moc_lancer.cpp: defines.h \
		figure.h \
		lancer.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) lancer.h -o moc_lancer.cpp

moc_nemnemtools.cpp: defines.h \
		nemnemtools.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) nemnemtools.h -o moc_nemnemtools.cpp

moc_nemnemwindow.cpp: ui_nemnemwindow.h \
		defines.h \
		gridmodel.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		colorselectbutton.h \
		systemtools.h \
		automate.h \
		gameboard.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		score.h \
		player.h \
		historian.h \
		nemnemwindow.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) nemnemwindow.h -o moc_nemnemwindow.cpp

moc_player.cpp: grid.h \
		defines.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		gridmodel.h \
		automate.h \
		gameboard.h \
		systemtools.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		historian.h \
		player.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

moc_score.cpp: defines.h \
		default.h \
		score.h
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) score.h -o moc_score.cpp

compiler_rcc_make_all: qrc_nem-nem.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_nem-nem.cpp
qrc_nem-nem.cpp: nem-nem.qrc \
		images/document-properties.svg \
		images/tetedeuxfleches.png \
		images/roll.png \
		images/document-open.svg \
		images/optionSounds.svg \
		images/papajaac.gif \
		images/relief.png \
		images/nem-nem-tete.png \
		images/preview-file.svg \
		images/window-close.svg \
		images/edit-undo.svg \
		images/help-contents.svg \
		images/ordiuneflechehaut.png \
		images/nemnemsplash.png \
		images/go-jump.svg \
		images/nem-nem-ordinateur.png \
		images/distrologo.png \
		images/nem-nem.png \
		images/teteuneflechehaut.png \
		images/go-down.svg \
		images/media-playback-start.svg \
		images/ordiuneflechebas.png \
		images/x-office-spreadsheet.svg \
		images/simple.png \
		images/document-revert.svg \
		images/document-new.svg \
		images/gtk-info.svg \
		images/teteuneflechebas.png \
		images/rollselected.png \
		images/document-save.svg \
		images/help-about.svg \
		images/chiffres.png \
		images/ordideuxfleches.png \
		images/applications-multimedia.svg \
		images/go-home.svg \
		images/view-refresh.svg \
		images/Nokia-QtCreator.png \
		images/go-up.svg \
		images/help-hint.svg \
		sounds/rollDice.wav \
		sounds/drumRoll.wav \
		sounds/applause.wav \
		sounds/newGame.wav
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/rcc -name nem-nem nem-nem.qrc -o qrc_nem-nem.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_nemnemwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_nemnemwindow.h
ui_nemnemwindow.h: nemnemwindow.ui
	/data/bin/QtSDK/Desktop/Qt/473/gcc/bin/uic nemnemwindow.ui -o ui_nemnemwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

automate.o: automate.cpp nemnemtools.h \
		defines.h \
		automate.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		candidate.h \
		gameboard.h \
		systemtools.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o automate.o automate.cpp

candidate.o: candidate.cpp candidate.h \
		coord.h \
		defines.h \
		cellule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o candidate.o candidate.cpp

cellule.o: cellule.cpp cellule.h \
		defines.h \
		coord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cellule.o cellule.cpp

colorselectbutton.o: colorselectbutton.cpp defines.h \
		colorselectbutton.h \
		default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorselectbutton.o colorselectbutton.cpp

coord.o: coord.cpp coord.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coord.o coord.cpp

default.o: default.cpp default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o default.o default.cpp

die.o: die.cpp die.h \
		defines.h \
		default.h \
		nemnemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o die.o die.cpp

dispenser.o: dispenser.cpp dispenser.h \
		defines.h \
		nemnemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dispenser.o dispenser.cpp

figure.o: figure.cpp figure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o figure.o figure.cpp

gameboard.o: gameboard.cpp gameboard.h \
		systemtools.h \
		default.h \
		defines.h \
		die.h \
		nemnemtools.h \
		mat.h \
		lancer.h \
		figure.h \
		sound.h \
		dispenser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameboard.o gameboard.cpp

grid.o: grid.cpp grid.h \
		defines.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		systemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid.o grid.cpp

gridmodel.o: gridmodel.cpp gridmodel.h \
		defines.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridmodel.o gridmodel.cpp

historian.o: historian.cpp historian.h \
		coord.h \
		defines.h \
		nemnemtools.h \
		nemnemevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historian.o historian.cpp

lancer.o: lancer.cpp lancer.h \
		defines.h \
		figure.h \
		nemnemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lancer.o lancer.cpp

main.o: main.cpp systemtools.h \
		nemnemwindow.h \
		ui_nemnemwindow.h \
		defines.h \
		gridmodel.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		colorselectbutton.h \
		automate.h \
		gameboard.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		score.h \
		player.h \
		historian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mat.o: mat.cpp mat.h \
		defines.h \
		default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mat.o mat.cpp

nemnemevent.o: nemnemevent.cpp nemnemevent.h \
		coord.h \
		defines.h \
		nemnemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nemnemevent.o nemnemevent.cpp

nemnemtools.o: nemnemtools.cpp nemnemtools.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nemnemtools.o nemnemtools.cpp

nemnemwindow.o: nemnemwindow.cpp nemnemwindow.h \
		ui_nemnemwindow.h \
		defines.h \
		gridmodel.h \
		grid.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		colorselectbutton.h \
		systemtools.h \
		automate.h \
		gameboard.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		score.h \
		player.h \
		historian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nemnemwindow.o nemnemwindow.cpp

player.o: player.cpp player.h \
		grid.h \
		defines.h \
		cellule.h \
		coord.h \
		lancer.h \
		figure.h \
		nemnemtools.h \
		candidate.h \
		gridmodel.h \
		automate.h \
		gameboard.h \
		systemtools.h \
		default.h \
		die.h \
		mat.h \
		sound.h \
		dispenser.h \
		nemnemevent.h \
		historian.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

score.o: score.cpp score.h \
		defines.h \
		default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o score.o score.cpp

sound.o: sound.cpp sound.h \
		defines.h \
		default.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sound.o sound.cpp

systemtools.o: systemtools.cpp systemtools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemtools.o systemtools.cpp

moc_automate.o: moc_automate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_automate.o moc_automate.cpp

moc_colorselectbutton.o: moc_colorselectbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_colorselectbutton.o moc_colorselectbutton.cpp

moc_die.o: moc_die.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_die.o moc_die.cpp

moc_gameboard.o: moc_gameboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameboard.o moc_gameboard.cpp

moc_grid.o: moc_grid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grid.o moc_grid.cpp

moc_gridmodel.o: moc_gridmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gridmodel.o moc_gridmodel.cpp

moc_historian.o: moc_historian.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historian.o moc_historian.cpp

moc_lancer.o: moc_lancer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lancer.o moc_lancer.cpp

moc_nemnemtools.o: moc_nemnemtools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nemnemtools.o moc_nemnemtools.cpp

moc_nemnemwindow.o: moc_nemnemwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nemnemwindow.o moc_nemnemwindow.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_score.o: moc_score.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_score.o moc_score.cpp

qrc_nem-nem.o: qrc_nem-nem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_nem-nem.o qrc_nem-nem.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

